# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS (Híbrida)
# ==========================================
# Usa la variable de Railway, si no existe, usa localhost (tu PC)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sportlogic_final?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# Esto evita el error "Unable to determine Dialect"
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=garzonandres2570@gmail.com
spring.mail.password=udof pybi kleq ygqt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# CONFIGURACIÓN DE SEGURIDAD Y VISTAS
# ==========================================
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true

# Recomendado para Railway: asegura que el servidor escuche en el puerto correcto
server.port=${PORT:8080}